//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RCP.Managers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RCP.Managers.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przerwa już trwa.
        /// </summary>
        internal static string BreakInProgress {
            get {
                return ResourceManager.GetString("BreakInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przerwa nie została rozpoczęta.
        /// </summary>
        internal static string BreakNotStarted {
            get {
                return ResourceManager.GetString("BreakNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozpoczęto przerwę.
        /// </summary>
        internal static string StarkBreak {
            get {
                return ResourceManager.GetString("StarkBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rozpoczęto pracę.
        /// </summary>
        internal static string StarkWork {
            get {
                return ResourceManager.GetString("StarkWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przerwa zakończona.
        /// </summary>
        internal static string StopBreak {
            get {
                return ResourceManager.GetString("StopBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praca zakończona.
        /// </summary>
        internal static string StopWork {
            get {
                return ResourceManager.GetString("StopWork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praca już trwa.
        /// </summary>
        internal static string WorkInProgress {
            get {
                return ResourceManager.GetString("WorkInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Praca nie została rozpoczęta.
        /// </summary>
        internal static string WorkNotStarted {
            get {
                return ResourceManager.GetString("WorkNotStarted", resourceCulture);
            }
        }
    }
}
